###############################################
#################  USUÁRIO  ###################
###############################################

# Criar usuário correto
POST http://localhost:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 1,
    "nome": "Marcella",
    "email": "marcella@gmail.com",
    "senha": "1234"
}

############################################
# Tentar Criar usuário correto com mesmo ID
POST http://localhost:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 1,
    "nome": "teste",
    "email": "marcella@gmail.com",
    "senha": "1234"
}

############################################
# Tentar Criar usuário sem @ no e-mail
POST http://localhost:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 2,
    "nome": "teste",
    "email": "testegmail.com",
    "senha": "1234"
}

###############################################
# Tentar Criar usuário com senha menor que 3 dígitos
POST http://localhost:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 2,
    "nome": "teste",
    "email": "testegmail.com",
    "senha": "12"
}

###############################################
# Pegar usuário por código
GET http://127.0.0.1:8000/usuario?id=1 HTTP/1.1
content-type: application/json

##############################################
# Pegar usuário por nome
GET http://127.0.0.1:8000/usuario/nome?nome=Marcella HTTP/1.1
content-type: application/json

###############################################
# Deletando usuário
DELETE http://127.0.0.1:8000/usuario/?id=1 HTTP/1.1
content-type: application/json

###############################################
################# ENDEREÇO ####################
###############################################

# Criar endereço
POST http://127.0.0.1:8000/endereco/1 HTTP/1.1
content-type: application/json

{
    "rua": "Rua Ladrilhadaaaa",
    "cep": "99999-999",
    "cidade": "São Paulo",
    "estado": "SP"
}

###############################################
# Buscar endereços do usuário
GET http://127.0.0.1:8000/usuario/1/enderecos/ HTTP/1.1
content-type: application/json

###############################################
# Deletar endereço pelo id_endereço
DELETE http://127.0.0.1:8000/endereco/2/ HTTP/1.1
content-type: application/json

###############################################
# Deletar endereço pelo id_usuário
DELETE http://127.0.0.1:8000/endereco/usuario/1/ HTTP/1.1
content-type: application/json

###############################################
#################### E-MAIL ###################
###############################################

#Buscar e-mail
GET http://127.0.0.1:8000/usuarios/emails/?dominio=gmail.com HTTP/1.1
content-type: application/json

###############################################
################### PRODUTO ###################
###############################################

# Criar produto
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "id": 1,
    "nome": "Sorvete",
    "descricao": "Doce gelado",
    "preco": 9.99
}

###############################################
# Criando outro produto
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "id": 2,
    "nome": "Pipoca",
    "descricao": "Doce",
    "preco": 1.99
}

###############################################
#Buscando produtos
GET http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

###############################################
#Deletando produto
DELETE http://127.0.0.1:8000/produto/1 HTTP/1.1
content-type: application/json

###############################################
################## CARRINHO ###################
###############################################

# Adicionanitem item no carrinho, usuario = 1, produto = 1 (Sorvete), quantidade = 3 
POST http://127.0.0.1:8000/carrinho/1/1/3 HTTP/1.1
content-type: application/json

{
    
}

###############################################
# # Adicionanitem item no carrinho, usuario = 1, produto = 2 (Pipoca), quantidade = 1
POST http://127.0.0.1:8000/carrinho/1/2/3 HTTP/1.1
content-type: application/json

{
    
}

###############################################
# Busca carrinho de um cliente 
GET http://127.0.0.1:8000/carrinho/1/ HTTP/1.1
content-type: application/json

###############################################
# Busca total carrinho de um cliente 
GET http://127.0.0.1:8000/carrinho/1/total HTTP/1.1
content-type: application/json

###############################################
# Deleta carrinho de um cliente 
DELETE http://127.0.0.1:8000/carrinho/1/ HTTP/1.1
content-type: application/json